name: Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v2
      
      - name: Validate Go releaser configuration
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: check
          
      - name: Release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Whatsapp Notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}
        uses: ishween/whatsapp-push-notify-action@master
      
      - name : Send Whatsapp Notify
        run: |
          echo Released new version!
